when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            # API Platform responses make this collection dominate the request.
            collect_serializer_data: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
